### ISSUE TITLE
Implement Random walk behavior

### ISSUE THREAD

**Issue by HarmlessEvil** [PaGr0m/RogueLike#34]

**Comment by PaGr0m** [comment]
@HarmlessEvil  Рандомное поведение - не подразумевает `target` в качестве игрока ?

**Comment by HarmlessEvil** [comment]
@PaGr0m я думал об этом. Я бы разделил на две итерации: простую без target и чуть сложнее — с ней

**Comment by PaGr0m** [comment]
Нужна консультация по #47
