### ISSUE TITLE
Create leveling system

### ISSUE THREAD

**Issue by HarmlessEvil** [PaGr0m/RogueLike#38]
Keep track of player's exp. Add exp score per kill

User should be able to use somehow:

`getLevel()` returns player's level
`getCurrentExp()` returns player's current exp
`getMaxExp()` returns maximum amount of exp on current player's level

User should be able to attach callback when player's level increases. It should be some `System.out.println()` for testing purposes

**Comment by karl-crl** [comment]
Check https://github.com/PaGr0m/RogueLike/pull/46
