### ISSUE TITLE
Describe serialization format for map

### ISSUE THREAD

**Issue by HarmlessEvil** [PaGr0m/RogueLike#39]
User should be able to load map from file. We need to create convenient format to describe the map.

Example:
```5 7
.......
...#...
...#...
...#...
P.###.Z
```

In this example file contains two numbers: `n` and `m`, which denote amount of rows and columns of a map respectively. `.` is an empty space, `#` is a wall, `Z` is zombie and `P` is player spawn position

**Comment by karl-crl** [comment]
Кажется, то что описал Саша, как пример, вполне рабочая схема. Дописала штуки, которые могут быть на мапе. (вроде я ничего не продолбала)

- tile (3 типа, вода ~ , трава . , стена # )
- Игрок ( P )
- Мобы (3 типа: зомби Z, босс X, пузырь S)
- Файербол ( F )
- Всякие бонусы (аптечки маленькая 1, средняя 2, большая 3, скорость 0)

**Comment by HarmlessEvil** [comment]
@karl-crl Как на карте может лежать файербол? Кажется, это лишнее)

**Comment by ZhekehZ** [comment]
У нас тайл хранит float) массив флотов -- самый простой способ хранить мапу

**Comment by ZhekehZ** [comment]
> @karl-crl Как на карте может лежать файербол? Кажется, это лишнее)

кажется, что достаточно сохранить позицию игрока и инвентарь (если карта автогенерируемая, то хранить ее не надо, она однозначно по позиции игрока восстанавливается)

**Comment by HarmlessEvil** [comment]
> У нас тайл хранит float) массив флотов -- самый простой способ хранить мапу

Речь о том, чтобы создать формат, в котором мы сможем создавать описания карт, которые можно загружать. Я вижу два основных требования:

* Чтобы легко читалось (и создавалось) человеком
* Чтобы легко парсилось программой

**Comment by HarmlessEvil** [comment]
Осталось это задокументировать)

**Comment by ZhekehZ** [comment]
Там пока есть небольшая бага при создании непрямоугольной карты. Пофикшу и напишу комменты

**Comment by ZhekehZ** [comment]
Изменил формат файла. Теперь он такой:
```
12
############
#p------z--#
#----#######
#----#
#-s--#######
#----~~~---#
############
```

**Comment by HarmlessEvil** [comment]
> Изменил формат файла. Теперь он такой:
> ...

Кул) А почему там одно число? Что оно значит?)
