### ISSUE TITLE
Unify coordinate system: migrate all classes to new coordinates

### ISSUE THREAD

**Issue by HarmlessEvil** [PaGr0m/RogueLike#42]
- [x] Use `IntCoordinate` in `Mover`
- [x] Use `IntCoordinate` in `DrawableDescriptor`
- [x] Constructor `IntCoordinate` from `IntCoordinate`
- [x] Add method `lenL2` and use in: `Camera.java` line `46`, `CowardlyBehavior.java` line `18`, `AggresievlyBehavior.java` line `18`
- [x] Add method `subtract`
- [x] Use coordinates in `EnemyBuilder`

**Comment by karl-crl** [comment]
Add PR https://github.com/PaGr0m/RogueLike/pull/43

**Comment by karl-crl** [comment]
Done
